Mve user management
ethanolmethanol/ft_transcendence42 pull request #30
Opened 2024-09-11 11:29 UTC by opaleboreale

2024-09-19 15:37 UTC, romann-broque requested changes

2024-09-19 15:37 UTC, romann-broque commented on back/transcendence_django/back_friends/views.py
> +    except json.JSONDecodeError:
add KeyError exception

2024-09-19 15:37 UTC, romann-broque commented on back/transcendence_django/back_friends/views.py
> +        friend_name = data.get("friendName")
use [] access instead of .get (to raise KeyError in the not_found case)

2024-09-19 15:37 UTC, romann-broque commented on back/transcendence_django/back_friends/views.py
Create a new class FriendshipView or use FriendshipManager model.

2024-09-24 15:09 UTC, romann-broque requested changes

2024-09-24 15:09 UTC, romann-broque commented on front/src/app/pages/friends-page/friends-page.component.css
> +  /* align-items: center; */
remove or uncomment

2024-09-24 15:09 UTC, romann-broque commented on front/src/app/pages/friends-page/friends-page.component.html
> +    <section class="friend-list">
create a new component:

```html
<app-friendlist [title]="Playing" [status]="PLAYING"></app-friendlist>
...
      <p>{title}</p>
      <section *ngIf="friendData.online.length > 0" class="avatar-list">
        <app-friend-card *ngFor="let friend of friendData.online" [friendName]="friend" [friendStatus]="{status}"></app-friend-card>
      </section>```

2024-09-25 09:34 UTC, romann-broque requested changes

2024-09-25 09:34 UTC, romann-broque commented on front/src/app/pages/friends-page/friends-page.component.ts
> +  async acceptRequest(event: { friendName: string, accept: boolean }): Promise<void> {
rename to acceptOrDeclineRequest

2024-09-25 09:34 UTC, romann-broque commented on front/src/app/services/friend/friend.service.ts
> +  public addFriend(friendName: string): Observable<any> {
Rename to requestFriendship

2024-09-26 08:49 UTC, opaleboreale commented on back/transcendence_django/shared_models/models.py
> +    def find_friend_request(from_user, to_user):
Not possible

2024-09-26 09:12 UTC, opaleboreale commented on front/package.json
> +    "@angular/material": "^18.2.0",
yes it is

2024-10-07 10:03 UTC, romann-broque requested changes

2024-10-07 10:03 UTC, romann-broque commented on front/src/app/pages/account-page/account-page.component.ts
> +      username: new FormControl('', [Validators.required, Validators.minLength(3), Validators.maxLength(20), usernameValidator()]),
use the new validators (from the shared folder)

2024-10-07 14:38 UTC, romann-broque approved these changes

2024-10-07 14:51 UTC, ethanolmethanol approved these changes
Finally getting there!

2024-10-08 14:57 UTC, romann-broque approved these changes

2024-10-08 14:59 UTC, merged